### ISSUE TITLE
Problems with Native library?

### ISSUE THREAD

**Issue by JYoung413** [JacisNonsense/Pathfinder#25]
I am having troubles implementing Pathfinder this year for my teams robot, a mentor says it is a problem with the native libraries not being found on the rio, here is the error messages the rio is spitting out.

`Warning  1  Robots should not quit, but yours did!  edu.wpi.first.wpilibj.RobotBase.main(RobotBase.java:224) 
 Warning at edu.wpi.first.wpilibj.RobotBase.main(RobotBase.java:224): Robots should not quit, but yours did! 
ERROR  1  Could not instantiate robot org.usfirst.frc.team125.robot.Robot!  edu.wpi.first.wpilibj.RobotBase.main(RobotBase.java:225) 
 Error at edu.wpi.first.wpilibj.RobotBase.main(RobotBase.java:225): Could not instantiate robot org.usfirst.frc.team125.robot.Robot! 
Warning  0  [Phoenix] Shutdown cleanly   
 ********** Robot program starting ********** 
 Platform: /Linux/arm/ 
ERROR  1  Unhandled exception instantiating robot org.usfirst.frc.team125.robot.Robot java.lang.UnsatisfiedLinkError: /usr/local/frc/lib/libpathfinderjava.so: libstdc++.so.6.0.20: cannot open shared object file: No such file or directory  java.lang.ClassLoader$NativeLibrary.load(Native Method) 
 Error at java.lang.ClassLoader$NativeLibrary.load(Native Method): Unhandled exception instantiating robot org.usfirst.frc.team125.robot.Robot java.lang.UnsatisfiedLinkError: /usr/local/frc/lib/libpathfinderjava.so: libstdc++.so.6.0.20: cannot open shared object file: No such file or directory 
 	at java.lang.ClassLoader$NativeLibrary.load(Native Method) 
 	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941) 
 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857) 
 	at java.lang.Runtime.loadLibrary0(Runtime.java:870) 
 	at java.lang.System.loadLibrary(System.java:1122) 
 	at jaci.pathfinder.PathfinderJNI.loadLibrary(PathfinderJNI.java:71) 
 	at jaci.pathfinder.PathfinderJNI.<clinit>(PathfinderJNI.java:27) 
 	at jaci.pathfinder.Pathfinder.generate(Pathfinder.java:46) 
 	at org.usfirst.frc.team125.robot.Robot.<init>(Robot.java:36) 
 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) 
 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) 
 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) 
 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
 	at java.lang.Class.newInstance(Class.java:442) 
 	at edu.wpi.first.wpilibj.RobotBase.main(RobotBase.java:216) `

**Comment by bdaroz** [comment]
See also: https://www.chiefdelphi.com/forums/showthread.php?t=161584

Talk about the last release being built w/ the 2017 not 2018 toolchain.

**Comment by JacisNonsense** [comment]
There are stable releases, they are on maven now. Instructions here: https://github.com/JacisNonsense/Pathfinder/blob/master/README.md#part-of-the-first-robotics-competition
